CREATE SCHEMA IF NOT EXISTS public;

DROP TABLE IF EXISTS public.audit_log CASCADE;

CREATE TABLE public.audit_log (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT '2026-03-01 00:00:00+00'
);

INSERT INTO public.audit_log (id, message, created_at) VALUES
    (1, 'unrelated fixture row one', '2026-03-01 11:00:00+00'),
    (2, 'unrelated fixture row two', '2026-03-02 11:00:00+00');

SELECT setval(pg_get_serial_sequence('public.audit_log', 'id'), (SELECT max(id) FROM public.audit_log), true);
