CREATE SCHEMA IF NOT EXISTS public;

DROP TABLE IF EXISTS public.order_items CASCADE;
DROP TABLE IF EXISTS public.orders CASCADE;
DROP TABLE IF EXISTS public.users CASCADE;

CREATE TABLE public.users (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email text NOT NULL UNIQUE,
    name text NOT NULL,
    active boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT '2026-01-01 00:00:00+00',
    CONSTRAINT users_email_check CHECK (position('@' in email) > 1)
);

CREATE INDEX users_name_idx ON public.users (name);

CREATE TABLE public.orders (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id integer NOT NULL,
    status text NOT NULL,
    total_cents integer NOT NULL,
    placed_at timestamptz NOT NULL,
    CONSTRAINT orders_total_cents_check CHECK (total_cents >= 0),
    CONSTRAINT orders_status_check CHECK (status IN ('pending', 'paid', 'shipped')),
    CONSTRAINT orders_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users (id)
);

CREATE INDEX orders_user_id_idx ON public.orders (user_id);

CREATE TABLE public.order_items (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id integer NOT NULL,
    sku text NOT NULL,
    quantity integer NOT NULL,
    unit_price_cents integer NOT NULL,
    CONSTRAINT order_items_quantity_check CHECK (quantity > 0),
    CONSTRAINT order_items_unit_price_cents_check CHECK (unit_price_cents >= 0),
    CONSTRAINT order_items_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders (id)
);

CREATE INDEX order_items_order_id_idx ON public.order_items (order_id);
CREATE UNIQUE INDEX order_items_order_sku_idx ON public.order_items (order_id, sku);

INSERT INTO public.users (id, email, name, active, created_at) VALUES
    (1, 'ada@example.test', 'Ada Lovelace', true, '2026-01-01 08:00:00+00'),
    (2, 'grace@example.test', 'Grace Hopper', true, '2026-01-02 09:30:00+00'),
    (3, 'alan@example.test', 'Alan Turing', false, '2026-01-03 10:45:00+00');

INSERT INTO public.orders (id, user_id, status, total_cents, placed_at) VALUES
    (10, 1, 'paid', 3500, '2026-02-01 12:00:00+00'),
    (11, 1, 'shipped', 1299, '2026-02-02 12:00:00+00'),
    (12, 2, 'pending', 500, '2026-02-03 12:00:00+00');

INSERT INTO public.order_items (id, order_id, sku, quantity, unit_price_cents) VALUES
    (100, 10, 'book-sql', 1, 2000),
    (101, 10, 'sticker-pg', 3, 500),
    (102, 11, 'mug-pg', 1, 1299),
    (103, 12, 'pin-elephant', 2, 250);

SELECT setval(pg_get_serial_sequence('public.users', 'id'), (SELECT max(id) FROM public.users), true);
SELECT setval(pg_get_serial_sequence('public.orders', 'id'), (SELECT max(id) FROM public.orders), true);
SELECT setval(pg_get_serial_sequence('public.order_items', 'id'), (SELECT max(id) FROM public.order_items), true);
